### PR TITLE
Use bytes buffer for logging server response

### PR DESCRIPTION
**Pull request by codenrhoden**
The Server response logger had sever fmt.Fprint*() calls that wrote
immediately to stdout, both before and after then call to the underlying
handler. If that handler also wrote to stdout, the response logging
could be very choppy.

This patch modifies the logger to build up the entire response in a byte
buffer, and then only emit the output to stdout at the very end.

Example output before this patch:
```
/csi.Node/NodeUnpublishVolume: REQ 0004: Version=minor:1 , VolumeId=values:<key:"name" value:"loop0" > , TargetPath=/mnt/loop0
/csi.Node/NodeUnpublishVolume: REP 0004INFO[0143] unmount command                               cmd=umount path=/mnt/loop0
: Reply=&{}
```
Note the **INFO.... unmount command** line appearing *in the middle* of the **REP**  line.
Here's what it looks like after the patch
```
/csi.Node/NodeUnpublishVolume: REQ 0003: Version=minor:1 , VolumeId=values:<key:"name" value:"loop0" > , TargetPath=/mnt/test
INFO[0031] unmount command                               cmd=umount path=/mnt/test
INFO[0031] unmount command                               cmd=umount path=/dev/disk/csi-blockdevices/.mounts/loop0
/csi.Node/NodeUnpublishVolume: REP 0003: Reply=&{}
```

### CODE REVIEW

**Comment by akutz** [comment]
Hi @codenrhoden,

True, but I specifically wrote it this way with the expectation if a user wants to log everything at once or in bits they're able to choose to do so by what they provide as the `io.Writer`. Note that the mock implementation provides an implementation of `io.Writer` that only writes the data once it encounters a newline:

```go
type logger struct {
	f func(msg string, args ...interface{})
	w io.Writer
}

func newLogger(f func(msg string, args ...interface{})) *logger {
	l := &logger{f: f}
	r, w := io.Pipe()
	l.w = w
	go func() {
		scan := bufio.NewScanner(r)
		for scan.Scan() {
			f(scan.Text())
		}
	}()
	return l
}

func (l *logger) Write(data []byte) (int, error) {
	return l.w.Write(data)
}
```

However, I don't see any reason that this patch shouldn't be used. 

I do have one request. Please refactor the patch so that it uses `Fprint` and its variants with the buffer as just another `io.Writer`. For example:

```go
fmt.Fprintf(b, "%s: ", info.FullMethod)
```

**Comment by codenrhoden** [comment]
Argh, I totally missed that, and you even provided an example of a
different Writer. Does that make this a non-issue? You said it's okay
anyways, but just making sure I'm not missing an easier solution.

**Comment by akutz** [comment]
Hi Travis,

No, I think this makes sense. I only did it the way I did because I knew the implementation was buffered, but it doesn't have to be. I may eventually update the interceptor to be more intelligent than just two writers, but I did that for now to be simple. I think you're right though that the interceptor's internal bits should buffer the output. I believe the reason I didn't was to control when the data would be flushed. That way if there was a partial entry it didn't have to be left hanging if I knew I could flush it any time by sending a new line.

**Comment by codenrhoden** [comment]
Will do!

**Comment by codenrhoden** [comment]
Made the change to use the `Fprint` calls again. I remember I had tried to do that the first time, as I thought `bytes.Buffer` would implement `io.Writer`, but wasn't passible a pointer the first time. Much simpler this way.

**Comment by codenrhoden** [comment]
@akutz. I'm mostly annoyed I didn't do that in the first place. :)

Should be good now.

**Pull request merged**
